### ISSUE TITLE
Allow termination/pause of monitored session

### ISSUE THREAD

**Issue by trevor-vaughan** [square/sudo_pair#18]
This looks great for monitoring what a user is doing but, should the person doing the monitoring determine that something bad is going on, they should be able to either pause the monitored person's ability to type or terminate the session immediately.

**Comment by stouset** [comment]
Pause isn't technically feasible, but it's easy to kill the session: [close the read end of the socket](https://github.com/square/sudo_pair/blob/master/sudo_pair/src/lib.rs#L171) (with the caveat that this only works the next time there's TTY output, so it doesn't work for actively-running commands with no output).

It's might be possible to be more aggressive about terminating a session even when there's a running command with no output (e.g., by having the approval script kill all children of the `sudo` process). I'm not sure the stance I want to take yet on what kind of features to add to the approval script; so far, I've taken the position that customizations to that script can and should take place by the users of this project themselves. But I'm open to considering ways of adding functionality to the script, as long as it's in a way that allows different users to easily opt in to or out of those features.
