### ISSUE TITLE
Compilation fails due to deny(warnings)

### ISSUE THREAD

**Issue by ignatenkobrain** [square/sudo_pair#53]
```rust
error: missing documentation for macro
   --> src/macros.rs:106:1
    |
106 | macro_rules! sudo_io_static_fn {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
note: lint level defined here
   --> src/lib.rs:21:9
    |
21  | #![deny(warnings)]
    |         ^^^^^^^^
    = note: #[deny(missing_docs)] implied by #[deny(warnings)]

error: missing documentation for macro
   --> src/macros.rs:182:1
    |
182 | macro_rules! sudo_io_fn {
    | ^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors

error: Could not compile `sudo_plugin`.
```

Using `deny(warnings)` is really bad idea since software would stop compiling after compiler update.

Please use `-D warnings` in CI instead.

**Comment by stouset** [comment]
I'm a bit confused since `deny(warnings)` doesn't appear anywhere in the source.

```$ rg -F 'deny(warnings)'
$```

**Comment by stouset** [comment]
I can't find any evidence there's an underlying issue here. There is nothing in the source that triggers failures on warnings.

**Comment by ignatenkobrain** [comment]
the deny(warnings) was removed in some commits few years ago but what's in master branch is not in sync with what is published on crates.io. If you simply publish new versions of sudo_plugin crates, this issue will be gone.
