### ISSUE TITLE
libsudopair.dylib Missing After Build

### ISSUE THREAD

**Issue by michael-leon** [square/sudo_pair#55]
`install -o root -g root -m 0644 ./target/release/libsudopair.dylib /usr/libexec/sudo`

This line in the installation script fails because `libsudopair.dylib` does not exist.  There are several `.rlib` items and I've tried installing them but nothing seems to put sudo_pair.so into `/usr/libexec/sudo/`

**Comment by stouset** [comment]
What are the contents of that directory?

**Comment by michael-leon** [comment]
Figured it out myself.  For future reference, the contents were: 

build     incremental      libsudo_plugin.d      libsudo_plugin_sys.rlib
deps      libsudo_pair.d   libsudo_plugin.rlib   native
examples  libsudo_pair.so  libsudo_plugin_sys.d

In my limited Rust knowledge/research, I found something that said .dylib is the .so for OSX so I ended up just moving libsudo_pair.so as sudo_pair.so into /usr/libexec/sudo and used the opt-out-of-individual-commands line and I started getting the prompts (not sure if both of those changes led to it working or just one individually)

**Comment by danielpops** [comment]
FWIW I also don't have the `.dylib` file(s). i built the code using a dockerfile that looks like

```
FROM rust
WORKDIR /code
ADD . /code
```

my `target` folder structure has same contents as @michael-leon 

```
root@f7f0e88cf22f:/code/target/release# ls -al
total 4432
drwxr-xr-x  7 root root    4096 Nov 18 22:46 .
drwxr-xr-x  3 root root    4096 Nov 18 22:46 ..
-rw-r--r--  1 root root       0 Nov 18 22:45 .cargo-lock
drwxr-xr-x 55 root root    4096 Nov 18 22:45 .fingerprint
drwxr-xr-x 22 root root    4096 Nov 18 22:45 build
drwxr-xr-x  2 root root   12288 Nov 18 22:46 deps
drwxr-xr-x  2 root root    4096 Nov 18 22:45 examples
drwxr-xr-x  2 root root    4096 Nov 18 22:45 incremental
-rw-r--r--  1 root root    1011 Nov 18 22:46 libsudo_pair.d
-rwxr-xr-x  2 root root 3750488 Nov 18 22:46 libsudo_pair.so
-rw-r--r--  1 root root     896 Nov 18 22:46 libsudo_plugin.d
-rw-r--r--  2 root root  628692 Nov 18 22:46 libsudo_plugin.rlib
-rw-r--r--  1 root root     194 Nov 18 22:46 libsudo_plugin_sys.d
-rw-r--r--  2 root root  102868 Nov 18 22:45 libsudo_plugin_sys.rlib
```

**Comment by danielpops** [comment]
Also, one more bit of context for why this happens: it's a linux vs osx thing, as per https://doc.rust-lang.org/reference/linkage.html =>

```
--crate-type=dylib, #[crate_type = "dylib"] - A dynamic Rust library will be produced. This is different from the lib output type in that this forces dynamic library generation. The resulting dynamic library can be used as a dependency for other libraries and/or executables. This output type will create *.so files on linux, *.dylib files on osx, and *.dll files on windows.
```
