### ISSUE TITLE
failed to run custom build command for sudo_plugin-sys v1.2.1

### ISSUE THREAD

**Issue by karekaa** [square/sudo_pair#65]
The execution of `cargo build --release` went OK, until this message:

  Compiling sudo_plugin-sys v1.2.1 (/home/<me>/git/sudo_pair/sudo_plugin-sys)
error: failed to run custom build command for sudo_plugin-sys v1.2.1 (/home/<me>/git/sudo_pair/sudo_plugin-sys)

Caused by:
  process didn't exit successfully: `/home/<me>/git/sudo_pair/target/release/build/sudo_plugin-sys-0d4f085cdf93c321/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to find libclang: "the `libclang` shared library at /usr/lib64/clang-private/libclang.so.7 could not be opened: libclangAST.so.7: cannot open shared object file: No such file or directory"', /home/<me>/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.53.2/src/lib.rs:1956:13

The strange thing is that both of those files mentioned above is actually there:
`ls -l /usr/lib64/clang-private/libclang.so.7
-rwxr-xr-x. 1 root root 558344 Jan 24  2019 /usr/lib64/clang-private/libclang.so.7
ls -l /home/<me>/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.53.2/src/lib.rs
-rw-rw-r--. 1 <me> <group> 80276 May  6 13:53 /home/<me>/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.53.2/src/lib.rs`

Any suggestions?

FYI:
I will suggest to add a list of less usual packages which needs to be installed. During the process I have done at least these:
`yum install cargo llvm llvm-devel`

**Comment by stouset** [comment]
Honestly I'm not sure. Is that file readable by your build user? Can you try setting the `LLVM_CONFIG_PATH` environment variable to the full path to an `llvm-config` binary? This is sometimes needed by [clang-sys](https://github.com/KyleMayes/clang-sys).

I'm working on pulling bindgen out as a compile-time dependency. I should only need to generate bindings once for x86 and once for amd64 platforms.

**Comment by karekaa** [comment]
Thanks for fast response, and sorry for my late response.
I see this from another computer, and will have a look on this on monday, I hope.
:-D

**Comment by karekaa** [comment]
This looks like some great progress!
1. Performed `git pull` which performed `19 files changed, 4481 insertions(+), 244 deletions(-)`
2. Tried: `cargo build --release` first, without defining `LLVM_CONFIG_PATH`
3. That went through, without any problems
`~/git/sudo_pair  on  master * $ cargo build --release
    Updating crates.io index
  Downloaded slog v2.5.2
  Downloaded slog-syslog v0.12.0
  Downloaded nix v0.14.1
  Downloaded syslog v3.3.0
  Downloaded void v1.0.2
  Downloaded time v0.1.43
  Downloaded log v0.3.9
  Downloaded unix_socket v0.5.0
   Compiling slog v2.5.2
   Compiling nix v0.14.1
   Compiling sudo_plugin-sys v1.2.1 (/home/<me>/git/sudo_pair/sudo_plugin-sys)
   Compiling void v1.0.2
   Compiling unix_socket v0.5.0
   Compiling time v0.1.43
   Compiling log v0.3.9
   Compiling syslog v3.3.0
   Compiling sudo_plugin v1.2.0 (/home/<me>/git/sudo_pair/sudo_plugin)
   Compiling slog-syslog v0.12.0
   Compiling sudo_pair v1.0.0 (/home/<me>/git/sudo_pair/sudo_pair)
    Finished release [optimized] target(s) in 25.79s
`
Thanks a lot!

**Comment by stouset** [comment]
Glad to hear it!
