### ISSUE TITLE
Issues with building RPM on RHEL 7.x

### ISSUE THREAD

**Issue by RiotNrrrd** [square/sudo_pair#82]
Hi, I built an RPM for _sudo-pair_ 0.11.1 on RHEL 7, and ran into a few small issues:

(1) Because the author apparently only built RPMs on Fedora 28/29/30, the _.spec_ file assumes a compliant version of _sudo_ is installed.

`[root@vm-rh7 SPECS]# grep ^Requires sudo-pair.spec`
`Requires: sudo`

Surely this should be

`Requires: sudo >= 1.9`

(2) In the _rpmbuild_ BUILD tree, I see the following:

`[root@vm-rh7 sudo_pair-sudo_pair-v0.11.1]# pwd`
`/var/local/mockbuild/rpmbuild/BUILD/sudo_pair-sudo_pair-v0.11.1`

`[root@vm-rh7 sudo_pair-sudo_pair-v0.11.1]# ls -l README.md`
`lrwxrwxrwx 1 mockbuild mock 21 Jun  8  2018 README.md -> ./sudo_pair/README.md`

I don't know if it's because of this, but when the RPM is built and installed, I get this error:

`[root@vm-rh7 rpmbuild]# rpm -ql sudo_pair`
`/usr/libexec/sudo/libsudo_pair.so`
`/usr/share/doc/sudo-pair-v0.11.1`
`/usr/share/doc/sudo-pair-v0.11.1/README.md`
`/usr/share/doc/sudo-pair-v0.11.1/sudo.conf`
`/usr/share/doc/sudo-pair-v0.11.1/sudo.prompt.pair`
`/usr/share/doc/sudo-pair-v0.11.1/sudo.prompt.user`
`/usr/share/doc/sudo-pair-v0.11.1/sudo_approve`

`[root@vm-rh7 rpmbuild]# cat /usr/share/doc/sudo_pair-v0.11.1/README.md`
`cat: /usr/share/doc/sudo_pair-v0.11.1/README.md: No such file or directory`

`[root@vm-rh7 rpmbuild]# ls -l /usr/share/doc/sudo_pair-v0.11.1/README.md`
`lrwxrwxrwx 1 root root 21 Jun 30 19:53 /usr/share/doc/sudo_pair-v0.11.1/README.md -> ./sudo_pair/README.md`

_README.md_ should be a plain file in the RPM, not a symbolic link pointing to nowhere.

(3) In _.../BUILD/sudo_pair-sudo_pair-v0.11.1/contrib_, there is a sample file called _sudo-pair.spec_.  Why is it _sudo-pair.spec_ and not _sudo_pair.spec_?

(4) Last but not least, in the final built RPM, there's no mention of _sudo_plugin_ or _sudo_plugin-sys_ anywhere.  Should there be?

(Editorial comment: The use of both _sudo_pair_ and _sudo-pair_ interchangeably is _very_ confusing.)

**Comment by stouset** [comment]
1. Yes, it should be >= 1.9.
2. Good catch, that should definitely not be a symlink to nowhere.
3. Because it was contributed by a third-party (for which I'm grateful) who presumably overlooked this :)
4. Why should there be? They're statically linked components of the plugin, so the fact that the project itself is internally comprised of multiple components seems like an irrelevant detail. I'm happy to hear opposing opinions.

I'm working on having a v2.0 of this project released shortly. I'll take a look at these issues and ensure the RPM spec is fixed in time for that release.

**Comment by RiotNrrrd** [comment]
>     4. Why should there be? They're statically linked components of the plugin, so the fact that the project itself is internally comprised of multiple components seems like an irrelevant detail.  I'm happy to hear opposing opinions.

It was just a naïve question, coming from ignorance.  I don't know anything about the _sudo_plugin_ stuff, I just noticed it didn't get built into the RPM, so that's why I asked if it should be in there  😄 

> I'm working on having a v2.0 of this project released shortly. I'll take a look at these issues and ensure the RPM spec is fixed in time for that release.

Yay!  Thanks a lot for responding.  I saw this feature demonstrated at SCaLE 18x in Todd's talk, and a co-worker prodded me into trying to build it as an RPM for RHEL 7 (which, alas, we're still standardized on).

**Comment by stouset** [comment]
We build it internally for RHEL 7 as well (just not as an RPM), so it should work! Please let me know if you run into any additional problems.

**Comment by RiotNrrrd** [comment]
> We build it internally for RHEL 7 as well (just not as an RPM), so it should work! Please let me know if you run into any additional problems.

I think if you can fix the "_Cargo build seems to cause the symlink-to-nowhere inside RPM_" issue, I'd be perfectly happy for now!

**Comment by stouset** [comment]
I think this should be closed now, please let me know if there are any outstanding issues.

**Comment by RiotNrrrd** [comment]
> I think this should be closed now, please let me know if there are any outstanding issues.

Thanks!  I'll give it a whirl when I'm working next.
