### ISSUE TITLE
Don't specify specific dependency versions in libraries

### ISSUE THREAD

**Issue by steven-joruk** [square/sudo_pair#97]
I think you should be as general as possible, and allow specific versions to be determined by users' `Cargo.lock`s.

**Comment by stouset** [comment]
Per [the cargo reference](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html), dependency versions like

```toml
[dependencies]
libc      = '0.2.70'
thiserror = '1.0'
```

are interpreted as semver version requirements. This is equivalent to specifying a version of `libc` that is `>= 0.2.70 and < 0.3` and a version of `thiserror` that is `>= 1.0` and `< 2.0`.
